name: docs

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Setup uv
          uses: astral-sh/setup-uv@v6

        - name: Install deps
          run: |
            uv venv
            uv pip install "mkdocs-macros-plugin>=1.4.0"

        - name: Build "module" docs
          run: |
            cd test/module
            uv run mkdocs build
        
        - name: Build "module_dir" docs
          run: |
            cd test/module_dir
            uv run mkdocs build